general {
    lock_cmd = hyprlock
    unlock_cmd = killall -q hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600 # 10 minutes in seconds
    on_timeout = loginctl lock-session
    on_resume = hyprctl dispatch dpms on
}

listener {
    timeout = 30 # 30 seconds
    on_timeout = hyprctl dispatch dpms off
    on_resume = hyprctl dispatch dpms on
}

# This ensures monitors turn off after 30 seconds even when locked
listener {
    timeout = 30 # 30 seconds
    on_timeout = if pgrep -x hyprlock > /dev/null; then hyprctl dispatch dpms off; fi
    on_resume = if pgrep -x hyprlock > /dev/null; then hyprctl dispatch dpms on; fi
    # Only activates when screen is locked
}
