music_directory      "/mnt/media-server/media/music"
bind_to_address      "localhost"

# Recommended location for database
playlist_directory      "~/.config/mpd/playlists"
db_file                 "~/.config/mpd/database"
state_file              "~/.local/state/mpd/state"

auto_update "yes"
restore_paused "no"

# Input
input {
        plugin          "curl"
}

# PipeWire output
audio_output {
        type            "pipewire"
        name            "Pipewire Output"
        format          "44100:16:2"
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}

decoder {
  plugin "opus"
  enabled "yes"
}

# ALSA output
#audio_output {
#        type            "alsa"
#        name                    "DSP"
#        options                 "dev=dsp"
#        device                  "plug:dmix"
#}

#mixer_type "software"
