name: "Evaluate Configurations"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eval-snowbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Evaluate Snowbox
        run: nix eval .#nixosConfigurations.snowbox.config.system.build.toplevel.drvPath

  eval-yoru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Evaluate Yoru
        run: nix eval .#darwinConfigurations.yoru.system.drvPath
