name: "Lint"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Statix
        run: nix run nixpkgs#statix -- check .
      - name: Deadnix
        run: nix run nixpkgs#deadnix -- --fail .
